export {
  buildGateAActionSet,
  supportsRegistration,
  toHexFelt,
  GATE_A_REGISTRATION_OPTIONS,
  type BuildGateAActionSetOptions,
  type GateAActionSet,
  type GateAShadowAccount,
  type FeltLike,
  type PrivacyClientLike,
  type PrivacyBuilderLike,
  type PrivacyCall,
  type RegistrableBuilderLike,
  type CollectPolicy,
  type CollectPolicyInput,
} from "./gate-a.js";

export {
  assertRecipientUnlinked,
  assertFundingDenomination,
  buildErc20ApproveCall,
  buildEkuboQuoteCall,
  buildEkuboSwapPlan,
  buildEndurStakePlan,
  LinkedRecipientError,
  FundingDenominationError,
  endurAdapter,
  ekuboAdapter,
  type ProtocolAdapter,
  type AdapterContext,
  type AppIntent,
  type EndurStakeIntent,
  type EkuboSwapIntent,
  type AdapterPlan,
  type AdapterSettlement,
  type BuildEndurStakePlanOptions,
  type BuildEkuboSwapPlanOptions,
  type EkuboRouteOptions,
} from "./adapters.js";

export {
  createOrRetainFacet,
  executeAppIntent,
  facetKey,
  moveFacet,
  recoveryPlan,
  type AssetKind,
  type FacetExecutor,
  type FacetPosition,
  type FacetRecord,
  type FacetState,
  type FacetStore,
} from "./facets.js";

export {
  deriveViewingKeyFromSignature,
  foldViewingKey,
  MAX_VIEWING_KEY,
  normalizeWalletSignature,
  VIEWING_KEY_LABEL,
} from "./wallet-identity.js";
