export {
  buildGateAActionSet,
  supportsRegistration,
  toHexFelt,
  GATE_A_REGISTRATION_OPTIONS,
  type BuildGateAActionSetOptions,
  type GateAActionSet,
  type GateAShadowAccount,
  type FeltLike,
  type PrivacyClientLike,
  type PrivacyBuilderLike,
  type PrivacyCall,
  type RegistrableBuilderLike,
  type CollectPolicy,
  type CollectPolicyInput,
} from "./gate-a.js";
