export {
  buildGateAActionSet,
  supportsRegistration,
  toHexFelt,
  GATE_A_REGISTRATION_OPTIONS,
  type BuildGateAActionSetOptions,
  type GateAActionSet,
  type GateAShadowAccount,
  type FeltLike,
  type PrivacyClientLike,
  type PrivacyBuilderLike,
  type PrivacyCall,
  type RegistrableBuilderLike,
  type CollectPolicy,
  type CollectPolicyInput,
} from "./gate-a.js";

export {
  assertRecipientUnlinked,
  assertFundingDenomination,
  buildErc20ApproveCall,
  buildEkuboQuoteCall,
  buildEkuboSwapPlan,
  buildEndurStakePlan,
  LinkedRecipientError,
  FundingDenominationError,
  endurAdapter,
  ekuboAdapter,
  type ProtocolAdapter,
  type AdapterContext,
  type AppIntent,
  type EndurStakeIntent,
  type EkuboSwapIntent,
  type AdapterPlan,
  type AdapterSettlement,
  type PublicRecipient,
  type BuildEndurStakePlanOptions,
  type BuildEkuboSwapPlanOptions,
  type EkuboRouteOptions,
} from "./adapters.js";

export {
  beginFacetRecovery,
  createOrRetainFacet,
  executeAppIntent,
  FACET_STATES,
  FACET_TRANSITIONS,
  facetKey,
  FacetLifecycleError,
  moveFacet,
  recoveryPlan,
  retireFacet,
  type AssetKind,
  type FacetExecutor,
  type FacetPosition,
  type FacetRecoveryPlan,
  type FacetRecord,
  type FacetState,
  type FacetStore,
  createMemoryFacetStore,
  createStorageFacetStore,
  listFacets,
  type KeyValueStorage,
} from "./facets.js";

export {
  assertFacetRecoverable,
  exitRoutesFromApps,
  planFacetRecovery,
  RECOVERY_REQUIRES_ADAPTER,
  RecoveryRouteError,
  type ExitRoute,
  type FacetRecoveryRouting,
  type RecoveryStep,
  type RecoveryStepAutomatic,
  type RecoveryStepUnsupported,
  type RecoveryStepViaExit,
} from "./recovery.js";

export {
  deriveRecoveryKey,
  isSealedRecoveryRecord,
  openRecoveryRecord,
  RECOVERY_KEY_LABEL,
  RECOVERY_RECORD_VERSION,
  saveSealedFacets,
  sealRecoveryRecord,
  loadSealedFacets,
  SEALED_FACETS_KEY,
  type SealedRecordStorage,
} from "./recovery-record.js";

export {
  deriveViewingKeyFromSignature,
  foldViewingKey,
  MAX_VIEWING_KEY,
  normalizeWalletSignature,
  VIEWING_KEY_LABEL,
} from "./wallet-identity.js";

export {
  buildWalletActions,
  ekuboHelperBinding,
  erc4626HelperBinding,
  ExecutorPolicyError,
  OPEN,
  QUEUED_REDEMPTION_VAULTS,
  OPEN_NOTE_PLACEHOLDER,
  submitPlan,
  WalletFacetExecutor,
  type HelperBinding,
  type RoutePolicy,
  type Strk20Action,
  type Strk20WalletLike,
  type WalletExecutorOptions,
} from "./executor.js";
